### ISSUE TITLE
Request for removal of leaked API key

### ISSUE THREAD

**Issue by sunnyden** [gaoxiaosong1113/node-mongDB#7]
Hi, I would like to know if you could remove my Google API key by replacing a dummy one (eg. `key=<Your-API-Key>&sensor=false`) and do a force update on this repo, because I am receiving a warning from Google Cloud and this may violate the ToS of GCP and I am unable to enable any further access control since the web page is still under development and the IP keeps changing. Thank you very much.

Files affected:
* [用户总览-地图总览.html](https://github.com/gaoxiaosong1113/node-mongDB/blob/f4d42fbb72a1bfcdeb513c7a4d363801c374ebce/public/web/%E6%99%BA%E4%BA%BA%E7%8E%AF%E5%A2%83%E7%89%A9%E8%81%94%E7%BD%91%E4%BA%91%E5%B9%B3%E5%8F%B0/%E7%94%A8%E6%88%B7%E6%80%BB%E8%A7%88-%E5%9C%B0%E5%9B%BE%E6%80%BB%E8%A7%88.html)

**Comment by gaoxiaosong1113** [comment]
ok  , thank you
